databaseChangeLog:
  - changeSet:
      id: create-application-documents-table
      author: system
      changes:
        - createTable:
            schemaName: recruitment_module
            tableName: application_documents
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: application_id
                  type: INT
              - column:
                  name: name
                  type: VARCHAR(100)
              - column:
                  name: document_url
                  type: VARCHAR(255)
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: created_by
                  type: INT
              - column:
                  name: deleted_at
                  type: TIMESTAMP 