databaseChangeLog:
  - changeSet:
      id: create-applications-table
      author: system
      changes:
        - createTable:
            schemaName: recruitment_module
            tableName: applications
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: job_description_id
                  type: INT
              - column:
                  name: first_name
                  type: VARCHAR(50)
              - column:
                  name: last_name
                  type: VARCHAR(50)
              - column:
                  name: email
                  type: VARCHAR(100)
              - column:
                  name: phone
                  type: VARCHAR(20)
              - column:
                  name: year_of_experience
                  type: INT
              - column:
                  name: education_level
                  type: VARCHAR(20)
              - column:
                  name: education_institution
                  type: VARCHAR(100)
              - column:
                  name: summary
                  type: TEXT
              - column:
                  name: status
                  type: VARCHAR(20)
              - column:
                  name: contact_link
                  type: VARCHAR(255)
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: created_by
                  type: INT
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: updated_by
                  type: INT
              - column:
                  name: deleted_at
                  type: TIMESTAMP 